POST http://127.0.0.1:8000/quote_creation HTTP/1.1
Content-Type: application/json

{
    "company_id": 1,
    "client_id": 16,
    "quantity": 1,
    "price_id": 15,
    "subscriptions": "['Liberty Wealth Planner', 'Deuxieme', 'troisième']",
    "accepted": 0
}