
POST http://127.0.0.1:8000/register_client HTTP/1.1
Content-Type: application/json

{
    "company_id": 1,
    "username": "jean",
    "password": "jean2130",
    "bankaccount": 1031891,
    "address": "12 boulevard de l'église Charleroi"
}

###

POST http://127.0.0.1:8000/subscription_creation HTTP/1.1
Content-Type: application/json

{
    "name": "Spotify",
    "active": 0,
    "price": 12
}

###

POST http://127.0.0.1:8000/quote_creation HTTP/1.1
Content-Type: application/json

{
    "company_id": 1,
    "client_id": 16,
    "quantity": 1,
    "subscriptions": "[1, 6, 8]",
    "accepted": 0
}

###
POST http://127.0.0.1:8000/accepting_quote HTTP/1.1
Content-Type: application/json

{
    "quote_id": 2,
    "client_id": 16,
    "accepted": 1

}

###

POST http://127.0.0.1:8000/convert_quote HTTP/1.1
Content-Type: application/json

{
    "quote_id": 2,
    "client_id": 16,
    "pending": 1
}

###

POST http://127.0.0.1:8000/invoice HTTP/1.1
Content-Type: application/json

{
    "client_id": 16
}

###

POST http://127.0.0.1:8000/pay_invoice HTTP/1.1
Content-Type: application/json

{
    "cardnumber": 79927398713,
    "currency": "USD",
    "invoice_id": 1
}
